### PR TITLE
Fix French translation

### PR DESCRIPTION
**Pull request by Bricabraque**

### CODE REVIEW

**Comment by deadhead420** [comment]
Thanks

**Comment by FredBezies** [comment]
Still busted for me... I'm kinda fed up with this busted display :(

**Comment by Bricabraque** [comment]
I'll also take a look right after the iso is downloaded

**Comment by deadhead420** [comment]
Looking at it now

**Comment by deadhead420** [comment]
Fixed. There was a quote in the wrong place. I have a utility called "shellcheck" which can be used to analyze shell scripts for errors. Ran it on arch-installer-french.conf and it gave me the exact line number the error was on.

**Comment by FredBezies** [comment]
Thanks for the info. Will use it next time.

**Pull request merged**
