### PR TITLE
fix VLC and add Full Username on user config and grml-zsh-config on zsh configuration

### PR DESCRIPTION
**Pull request by viviengraffin**
Hello,
I have :   
 - add qt4 and phonon-qt4-vlc on vlc install
 - add grml-zsh-config on zsh configuration menu
 - add full username on creation of user and this edition

### CODE REVIEW

**Comment by FredBezies** [comment]
Yummy! And I don't have to translate lines :)

Can't wait to see it commited :)

**Comment by viviengraffin** [comment]
I see that. I Forget that

**Comment by viviengraffin** [comment]
I have forget that

**Comment by viviengraffin** [comment]
I test my changes

**Comment by FredBezies** [comment]
You're missing something in line 104 in lib/configure_base.sh

shell+=" grml-zsh-config zsh-completions" -> shell+=" grml-zsh-config zsh-completions zsh-syntax-highlighting"

Will try to find another bugs.

**Comment by viviengraffin** [comment]
I test my other changes before push it

**Comment by FredBezies** [comment]
@viviengraffin please, don't take it bad! I just wanted to help here :(

By the way, great job!

**Comment by FredBezies** [comment]
@viviengraffin please, don't take it bad! I just wanted to help here :(

By the way, great job! :)

**Comment by viviengraffin** [comment]
thanks I fix a bug with fullname of user

**Comment by FredBezies** [comment]
@viviengraffin : you're welcome. And if you need some more beta-test, just tell me! I'll be happy to help.

**Comment by viviengraffin** [comment]
Thanks but I have already know the problem

**Pull request merged**
