### PR TITLE
Fixing some typos :)

### PR DESCRIPTION
**Pull request by FredBezies**
Thanks Bricabraque for the update on my previous work. Fixing some typos I saw.

### CODE REVIEW

**Comment by deadhead420** [comment]
Thanks man!!

**Comment by Bricabraque** [comment]
You're welcome fred !

**Comment by FredBezies** [comment]
@Bricabraque Working alone on a translation is an hard work. I used previous translation, but some of them I left were kinda... rough :) 

By the way, we can work both on this file, in order to fix it when new additions are made. And @deadhead420 , it is a pleasure to help your project.

**Comment by Bricabraque** [comment]
Sounds great for me !

**Comment by FredBezies** [comment]
@Bricabraque We have a deal :D

**Pull request merged**
