### PR TITLE
Update italian translation

### PR DESCRIPTION
**Pull request by Bricabraque**
Italian translation is now complete.

### CODE REVIEW

**Comment by deadhead420** [comment]
Cool, cool, thanks man!

**Comment by deadhead420** [comment]
Great!! Looks like this is totally ready to go. Thanks a lot man. Adding to install script and testing now, will be released with 2.2.7 in one week.

**Comment by Bricabraque** [comment]
Well, I've just seen you added a line for the intel ucode, I'll update it these days. ;)

**Comment by deadhead420** [comment]
Sounds good!! Will let you know when I release. Building new ISO now to test your language. Will let you know how it works

**Pull request merged**
