### PR TITLE
Update arch-installer-french.conf

### PR DESCRIPTION
**Pull request by FredBezies**
Adding xfs line and some little tweaks.

### CODE REVIEW

**Comment by deadhead420** [comment]
Has French been fixed or is it still broken due to that other pull request?

**Comment by FredBezies** [comment]
@deadhead420 still broken. Not a single line printed on first page after choosing french.

No text on buttons... But sometimes I have some texts in some parts :(

**Comment by FredBezies** [comment]
Tried to grab arch-anywhere 2.2.7 translation file. Still busted. Any idea?

**Comment by deadhead420** [comment]
@FredBezies can revert to old file before that pull request was merged

**Pull request merged**
