### PR TITLE
Fix for bug #395

### PR DESCRIPTION
**Pull request by FredBezies**
Just a guess to work around this bug. Not the cleanest one, but it seems to work :)

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
@deadhead420 related to #383

**Comment by pnedkov** [comment]
Yes, this should fix it. Before I merge it, could you please update the commit message to something that is not a question and does not include a issue number? "Fix package name" or something similar will suffice. Thanks.

**Comment by FredBezies** [comment]
@pnedkov : fixed :)

I will wait until it is applied, and I will make another ISO image from git repository :)

**Comment by pnedkov** [comment]
You have to force push.

**Comment by FredBezies** [comment]
How can I force push? I don't have write access to the repository. Sorry for this noob question :(

**Comment by FredBezies** [comment]
Ouch! How can I force a push? I don't have write access to do so... Or am I wrong?

**Comment by pnedkov** [comment]
You force push to your repo/branch. The pull request will be updated automatically.

**Comment by FredBezies** [comment]
I'm getting lost. Can't you make this patch for me, please?

**Comment by pnedkov** [comment]
It should be something like this:

# go to your patch-3 branch
git checkout patch-3

# amend the last commit
git commit --amend -m "Fix package name"

# force push
git push --force

**Comment by FredBezies** [comment]
I was trying to do it using github. But, it will be simpler to you to make my patch working :)

**Comment by FredBezies** [comment]
Thanks!

**Pull request merged**
