### PR TITLE
Added WindowMaker translated lines :)

### PR DESCRIPTION
**Pull request by FredBezies**
Is this to quick? 🗡 

Based on this commit: https://github.com/deadhead420/arch-linux-anywhere/commit/f579a1ffe1f4b4106de9b6bfef1e422b995b7f49

### CODE REVIEW

**Comment by deadhead420** [comment]
not at all. I will be adding more soon

**Comment by deadhead420** [comment]
Really big update I just did I'm about to test, probably added around 200 lines

**Comment by FredBezies** [comment]
15 to 20? Oo!

Well, I'll need some coffee to work on translation soon :)

**Comment by deadhead420** [comment]
Testing then I will push changes

**Pull request merged**
