### PR TITLE
Master

### PR DESCRIPTION
**Pull request by teacher4711**

### CODE REVIEW

**Comment by deadhead420** [comment]
Great! Merged! Will be doing a release very soon

**Comment by deadhead420** [comment]
I added one more line to the german file "failed_msg=" should be the last thing I add before release... I also made some changes concerning colors to the english file which I made to none of the translation files.To make the changes in the german file you can do the following. Search and replace every occurance of: * 
replace with: $a

Then do another search and replace for: \Z2<\Z1#\Z2>\Zn
replace it with: $h

Then at the bottom of the translation, where it says do not edit below this line but above the if statement add in the following (see english file for where to add at bottom):
a="\Z2*\Zn"
h="\Z2<\Z1#\Z2>\Zn"

Then also search and replace Error: (in your language) with:
$error

At the top of main_msg() (above yes="Yes") add in:

error="\Z1Error:\Zn" (in your own language)

**Comment by deadhead420** [comment]
I went ahead and made the changes for you just one line which needs to be translated. I'm going to do a release. The line which needs translated is for a menu which will never be seen 99.9% of the time. Its an error menu for if the install fails and is very rare so it doesn't matter if its translated for this release.

**Comment by deadhead420** [comment]
Also... I Just tested the german installer. That issue with the buttons not being big enough and overlapping is no more. I changed the entire installer from whiptail menus over to dialog and the whole interface has improved drastically! The buttons are spaced beautifully now in the german installer.

**Comment by teacher4711** [comment]
Super. That sounds great. Really looking forward to the new menus.

It might sound like a novice question but if you can spare some time, could
you briefly describe the steps how to work with github? E.g.
a) Do you use terminal or a desktop program (and which one)
b) How you pull and push
c) How you synchronize and keep your branch up to date.

I seem to be running into merging issues all the time.

For security reasons I just send you the latest translations you described
in your mail in the attachment again.

Regards.
Michael

2016-06-13 1:00 GMT+02:00 deadhead <notifications@github.com>:

**Pull request merged**
