### PR TITLE
Add f2fs Support 

### PR DESCRIPTION
**Pull request by frap129**
This PR adds the option to use f2fs as the main filesystem, and installs the latest GRUB with a patch for f2fs support for /boot.

### CODE REVIEW

**Comment by frap129** [comment]
@deadhead420

**Comment by deadhead420** [comment]
Hey man. Thanks for this. Have you tested? Is everything working as it should?

**Comment by frap129** [comment]
I tested it once when setting up my desktop. Everything went well for me. There should probably be a notice that it will only work on SSD's

**Comment by deadhead420** [comment]
Looking over things I'll be able to add the feature but it will not work properly if I merge this. Is there a reason for adding grub to the iso? To create a partition you only need f2fs-tools, the lines with grub should be removed and are not needed (the iso uses syslinux). I will also need a command that checks if the drive is using nand flash and if not it wont even display the option. A command will need to be added to etc/arch-anywhere.conf example:

if (command to check for ssd); then f2fs=true ; else f2fs=false ; fi

Then that will need to be used in the main script to select fs, would be much easier to create 1 function to select fs then call that function rather than having 4 different areas where you can select. Then in that function will be:

fs_select() {

if $f2fs ; then
   show filesystem select menu with f2fs inculded
else
   show filesystem select menu without f2fs
fi

}

Then in the install_base function f2fs-tools will need to be added to the install if fs=f2fs. And after the install the initramfs will need to be regenerated while in a chroot.

I will be able to get this feature working but it will take a bit more coding a quite a bit more testing to be sure its working correctly.

**Comment by deadhead420** [comment]
I found a command to check for ssd: 

cat /sys/block/sda/queue/rotational

**Comment by frap129** [comment]
I guess I interpreted the script wrong. The grub-f2fs packages needs to get installed on the PC that is using f2fs. Grub doesn't have native f2fs boot support, so either /boot needs to be on a separate ext4 partition or use the f2fs patched grub.  I figured it would be easier to just install the patched grub on all systems, rather than try to create a standalone boot partition. How would I go about automating the installation on the host pc? I manually installed it using chroot before I added it to the ISO

**Comment by frap129** [comment]
I guess i interpreted the script wrong. GRUB doesn't have f2fs boot support without the patched version, so either the

**Comment by deadhead420** [comment]
I've got it setup and testing now... I went with creating a seperate boot partition... I guess I could add support for grub-f2fs but it would need to be pre-compiled and thrown on the iso with my other aur packages (located in /usr/share/arch-anywhere/pkg on the iso). I've got everything working for now but boot cant be f2fs. Autopartition only uses ext4 for boot by default and in manual partition I have removed f2fs from the options when mountpoint is boot.... Adding grub-f2fs wouldnt be hard but It would need to be pre-compiled in creator.sh script (see where I pre-compile fetchmirrors and arch-wiki near the top of creator.sh then copy over to iso at /usr/share/arch-anywhere/pkg)

**Comment by deadhead420** [comment]
Going to close this pull request. f2fs will be in the next release when using both auto or manual partitioning. You had the right idea with your changes however the script it a bit more complex so I had to change some stuff to actually impliment this but all is working good now. Support for booting from f2fs is not included. If using f2fs autopartition still creates /boot in ext4, when using manual partitioning if you select your root partition as f2fs it will not let you continue until you create a boot (doesn't list f2fs as an option for /boot). This feature will be in the next release on the 1st of the month.

**Comment by vinibali** [comment]
support for f2fs seems to be missing from the current release.

**Pull request closed without merging**
