### PR TITLE
Resolve Issue #265

### PR DESCRIPTION
**Pull request by PatrickNByrne**
Fix a typo that caused issue #265

### CODE REVIEW

**Comment by deadhead420** [comment]
This has already been fixed

**Comment by deadhead420** [comment]
Shit actually there are a few lines which haven't been fixed good eye, thanks

**Comment by PatrickNByrne** [comment]
Great, thanks!

**Comment by deadhead420** [comment]
Removed the whitespace at the end of the lines as it is only needed at the beginning. Thanks for bringing this up again, didn't notice those few lines. I'm doing a release now with the patch so people stop bringing it up

**Pull request merged**
