### PR TITLE
Line 225 translated

### PR DESCRIPTION
**Pull request by teacher4711**
As requested, I translated line 225.

### CODE REVIEW

**Comment by deadhead420** [comment]
Thanks man! I've added quite a few new dialog menus... I've actually added, removed, and changed a lot of stuff in the english file however I haven't updated any of the language files yet. Don't have time at the moment. I've removed over 2000 lines from the installer and added 917 just in the past few days. If you wanna take a look at the history on github for the english.conf file you will see all the changes I've made and what I have added / removed / changed.

**Comment by deadhead420** [comment]
Wont let me merge for some reason...

**Comment by teacher4711** [comment]
I'm finished translating your numerous changes
Could you please look at "user_exists_msg". The message does not match a
"user exists" message.

You might like to consider the following:
desktop_cancel_msg: dont --> don't
part_frmt_msg: formating --> formatting

nwmanager_msg0 equals nwmanager0_msg but here the '=' is missing
nwmanager_msg1 equals nwmanager1_msg

manual_part_var1 Note will --> Note: Will

Since there was obviously a merging problem, I also attach the latest
German translation.

You really put a lot of effort into the project!

Regards,
Michael

2016-06-10 20:18 GMT+02:00 deadhead <notifications@github.com>:

**Comment by deadhead420** [comment]
Thanks man! Great work! I'm going to close this because it has conflicts. The code in your branch is behind mine. Need to pull the new updates from my branch before it will let me merge with no conflict. I've copied the translated file from your branch into the german file in my branch and will push the changes soon.

**Comment by deadhead420** [comment]
I've also updated the english file with the changes you mentioned above. Good eye!

**Pull request closed without merging**
